language: perl6
os:
  - linux
  - osx
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -r t/
sudo: false
matrix:
   allow_failures:
      - os: osx
